### ISSUE TITLE
Where do I find the certificate? VOCES or FOCES?

### ISSUE THREAD

**Issue by ChristianGerdes** [nodes-php/nemid#10]
Hi,

The code doesn't work for me and I think it's because of my certificate. Where do I find my certificate? Can I use anyone of these?
https://www.nets.eu/dk-da/kundeservice/nemid-tjenesteudbyder/NemID-tjenesteudbyderpakken/Pages/OCES-II-certifikat-eksempler.aspx

- Christian

**Comment by lsv** [comment]
Fixed in #11 
[Just read Test.md implementation](https://github.com/nodes-php/nemid/blob/master/Test.md) :)
