### ISSUE TITLE
Invalid target origin '{https://appletk.danid.dk/}'

### ISSUE THREAD

**Issue by RahibAly** [nodes-php/nemid#21]
I'm getting following error in the console on test environment:
(index):35 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin '{https://appletk.danid.dk/}' in a call to 'postMessage'.
    at onNemIDMessage (http://localhost/NemID/:35:18)

**Comment by Casperhr** [comment]
did you add a form for postMessage?

check here for laravel inspiration https://github.com/nodes-php/nemid/tree/master/inspiration

**Comment by RahibAly** [comment]
Nevermind it was a syntax error where I needed to add a curly bracket.
Now I'm getting another error:
inject.preload.js:373 GET blob:https://appletk.danid.dk/3abd0880-e5ee-4241-82df-344361939bc0 0 ()

**Comment by RahibAly** [comment]
UPDATE: Its fixed with SSL.
can you tell me how I can get a test account?

**Comment by Casperhr** [comment]
Let me google that for you :)
https://www.nemid.nu/dk-da/erhverv/

**Comment by Casperhr** [comment]
"NemID tjenesteudbyder"

its 1699 kr and takes 1month to get IP white listed. Generally a fairly annoying process

**Comment by RahibAly** [comment]
Thanks

**Comment by RahibAly** [comment]
I have loaded the iframe successfully, now setting up the callback function, but unfortunately, After login with test account, I'm getting following errors can you guide me to fix these? I'm doing it on core PHP, Not using laravel

Notice: Undefined variable: certsbysubject in /NemID/vendor/nodes/nemid/src/Login/CertificationCheck/CertificationCheck.php on line 401

Notice: Undefined variable: certsbysubject in /NemID/vendor/nodes/nemid/src/Login/CertificationCheck/CertificationCheck.php on line 406

Notice: Undefined offset: 1 in /NemID/vendor/nodes/nemid/src/Login/CertificationCheck/CertificationCheck.php on line 414

Fatal error: Uncaught Error: Call to undefined method Nodes\NemId\Login\CertificationCheck\Exceptions\InvalidCertificateException::getResponse() in /NemID/callback.php:43 Stack trace: #0 {main} thrown in /NemID/callback.php on line 43

**Comment by Casperhr** [comment]
This looks like you are not submitting the certificate correctly from the iframe

try to log what you receive

**Comment by Casperhr** [comment]
Feel free to PR another inspire afterwards for vanilla php

**Comment by RahibAly** [comment]
Here is what Exception message says: Couldn't find leaf certificate
even though VOCES certificate is included

**Comment by Casperhr** [comment]
Ok either there is something wrong with your certificates or the signing might be wrong. I remember when I build it, that you can get iframe to work but the output is still invalid

In the bottom of the xml output certificate, can you find a PID and name?

**Comment by RahibAly** [comment]
Not sure where to check for PID and name?

I'm getting the error here:
try {
            $userCertificate = new CertificationCheck($config);
            $certificate = $userCertificate->checkAndReturnCertificate($response);
            print_r($certificate);
        } catch (\Exception $e) {
            $result['getMessage'] = $e->getMessage();
            $result['getLine'] = $e->getLine();
}

Array
(
    [getMessage] => Couldn't find leaf certificate
    [getLine] => 415
)

**Comment by Casperhr** [comment]
Yes I get that, try to log the response

**Comment by RahibAly** [comment]
After base64_decode, this is $response value: "AUTH007"

Error: CertificationCheck.php on line 415

**Comment by RahibAly** [comment]
I figured it out that was a bad test account, so I tried with another one and error has changed now:
Array
(
    [getMessage] => Certificate chain not signed by any trustedroots
    [getLine] => 212
)

**Comment by Casperhr** [comment]
super. yes this is why there is an xml checker.

successful login gives xml
failed logins gives base_64 string error code

lovely system indeed

**Comment by RahibAly** [comment]
so what does this error means? "Couldn't find leaf certificate"? what to do next?

**Comment by RahibAly** [comment]
Thanks for your guidance.

**Comment by Casperhr** [comment]
np

**Comment by RahibAly** [comment]
Hi, what does this error means and how can I fix it?
[Message] => Certificate chain not signed by any trustedroots
[Line] => 212
[File] => /NemID/vendor/nodes/nemid/src/Login/CertificationCheck/CertificationCheck.php

**Comment by Casperhr** [comment]
This means that the certficate you get back (xml doc) is not signed, might be invalid. can you check the bottom of it if 
PID and name is there?

if you are in php7 you need to disable checkOcsp

**Comment by RahibAly** [comment]
Yes, I'm using php7, disabled checkOcsp, But where and how can I check PID and Name?

**Comment by RahibAly** [comment]
I have printed this "$certificateChain = $this->xml2certs($xp, $x509);"
and I'm getting PID and Name, but I'm getting error after $this->simpleVerifyCertificateChain($certificateChain); function..
