### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by FrittenKeeZ** [nodes-php/nemid#22]
When generating `certifikateAndPrivateKey` I'm not prompted to input a password apart from the import password - am I missing something?
```sh
openssl pkcs12 -in path.p12 -out certicateAndPrivateKey.pem -nocerts -nodes
```

Does this package work with the javascript solution?

What do I input for `serviceID`? Is it the same as `EntityID` you make for the metadata file uploaded to https://administration.nemlog-in.dk?

**Comment by Casperhr** [comment]
I cannot not help you with the signing of certificates. but you have -nodes in your command. might be the problem

This package is the js solution. it's a iframe with form submit.
ServiceId is a number you get which is your "app id". not sure if its same as entityID

A lot of the questions you have is setting up your company, danid is there to help with that. Or you can try a bit your self, it's manageable to figure out. The guide here should do it
