### ISSUE TITLE
checkOscp gives cURL error

### ISSUE THREAD

**Issue by zubfatal** [nodes-php/nemid#33]
Using a test certificate and a test user, when `checkOscp` is enabled i get the following error:
`Failed to check certificate: cURL error 56: Recv failure: Connection reset by peer (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

I have not tried this against the production environment, so I'm not sure if it's related to using the test environment.

Did a bit of debugging, and it seems it tries to send the request to: http://ocsp.systemtest34.trust2408.com/responder if that helps.

**Comment by Kodzila** [comment]
I have exactly the same issue. I wrote to NEMID support that everything is fine on their side.

It started to working for me when I changed:
```
            $params = [
                'headers'         => [
                    'Content-type: application/ocsp-request'."\r\n",
                ],
                'body'            => $ocsPreq,
                'connect_timeout' => 10,
            ];
```
to:
```
            $params = [
                'headers'         => [
                    'Content-type: application/ocsp-request',
                ],
                'body'            => $ocsPreq,
                'connect_timeout' => 10,
            ];
```

**Comment by zubfatal** [comment]
Thanks @Kodzila you're right, it works without `."\r\n"` actually according to https://docs.guzzlephp.org/en/stable/request-options.html#headers i think it should be:
```php
            $params = [
                'headers'         => [
                    'Content-type' => 'application/ocsp-request',
                ],
                'body'            => $ocsPreq,
                'connect_timeout' => 10,
            ];
```

Not really sure if Guzzle does a check and converts headers if they are in http header format, but it seems to work either way as long as `\r\n` is omitted.
