### ISSUE TITLE
 Certificate chain not signed by any trustedroots

### ISSUE THREAD

**Issue by johnmcclanes001** [nodes-php/nemid#37]
Fatal error: Uncaught Nodes\NemId\Login\CertificationCheck\Exceptions\InvalidCertificateException: Certificate chain not signed by any trustedroots in /var/www/html/test/nemid/src/Login/CertificationCheck/CertificationCheck.php:212 Stack trace: #0 /var/www/html/test/nemid/src/Login/CertificationCheck/CertificationCheck.php(100): Nodes\NemId\Login\CertificationCheck\CertificationCheck->simpleVerifyCertificateChain(Array) #1 /var/www/html/test/nemid/validateCPR.php(21): Nodes\NemId\Login\CertificationCheck\CertificationCheck->checkAndReturnCertificate('<?xml version="...') #2 {main} thrown in /var/www/html/test/nemid/src/Login/CertificationCheck/CertificationCheck.php on line 212

In browser I have logged with test user and got base64 response
using that response I am trying to call pidCprRequest()
Please let me know if anything missing

Here is my code.
$response = base64_decode($base64Response);
require __DIR__.'/vendor/autoload.php';
ini_set('display_errors', 1);
error_reporting(E_ALL & ~E_WARNING & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT & ~E_USER_NOTICE & ~E_USER_DEPRECATED);
$response = "base 64 response after login using nemid and password";
$check = CertificationCheck::isXml($response);

$config = include __DIR__.'/config/nemid.php';

$config['test'] = true;
$config['login']['testSettings']['privateKeyPassword'] = 'Test1234';
$config['login']['testSettings']['privateKeyLocation'] = __DIR__.'/testcertificates/test_private.pem';
$config['login']['testSettings']['certificateLocation'] = __DIR__.'/testcertificates/test_public.pem';
$userCertificate = new CertificationCheck($config);

$certificate = $userCertificate->checkAndReturnCertificate($response);

$certificate->getSubject()->getName();

$pid = $certificate->getSubject()->getPid();

$pidCprMatch = new PidCprMatch(config('nodes.nemid'));

$response = $pidCprMatch->pidCprRequest($pid, $certificate);

$isCPRValid = $response->didMatch();
print_r($isCPRValid);

**Comment by rasmusebbesen** [comment]
did you read #32 before posting this?

**Comment by johnmcclanes001** [comment]
After posting I read and issue is resolved.
One more help I need.
Please help.
I have received below response for 

$pid = $certificate->getSubject()->getPid();
$response = $pidCprMatch->pidCprRequest($pid, '3112743356');

can you tell me what I am missing?
 
Nodes\NemId\Webservice\PidCprMatch\Responses\Response Object
(
    [code:protected] => -1
    [short:protected] => Exception
    [danish:protected] => Client error: `POST https://pidws.pp.certifikat.dk/pid_serviceprovider_server/pidxml/` resulted in a `403 Forbidden` response:
Access denied

    [english:protected] => Client error: `POST https://pidws.pp.certifikat.dk/pid_serviceprovider_server/pidxml/` resulted in a `403 Forbidden` response:
Access denied

)

**Comment by rasmusebbesen** [comment]
It seems you are not allowed to do the request. Perhaps you are missing something in your service agreement with Nets?

You can read about the services here https://www.nets.eu/dk-da/l%C3%B8sninger/nemid/nemid-tjenesteudbyder/supplerende-tjenester/pid-rid-cpr-tjenester

closing this issue.
